# Generated by Django 5.2 on 2025-04-28 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_booking_travel_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
