# Generated by Django 5.2 on 2025-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_package_price_package_image2_package_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='Description',
            field=models.TextField(default=100),
            preserve_default=False,
        ),
    ]
