# Generated by Django 5.2 on 2025-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_vehicle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=100, upload_to='vehicles/'),
            preserve_default=False,
        ),
    ]
