# Generated by Django 5.2 on 2025-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='perhead',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
