# Generated by Django 5.2 on 2025-05-15 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_vehicle_perhead_booking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='travel_package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.package'),
            preserve_default=False,
        ),
    ]
